### ISSUE TITLE
High CPU utilization making HA unresponsive

### ISSUE THREAD

**Issue by barto64** [rgc99/irrigation_unlimited#104]
## Version of the custom_component
2023.2.1

HA version 2023.4.4
Supervisor 2023.04.0
Operating System 9.5

HA is excuted on a HA Blue Hw 

## Configuration
irrigation_unlimited:
  refresh_interval: 1
  controllers:
    name: "Jardin MP"
    zones:
      - name: "Cesped 1"
        entity_id: "switch.sonoff_10006fb002_2"
      - name: "Cesped 2"
        entity_id: "switch.sonoff_10006fb002_3"
      - name: "Cesped 3"
        entity_id: "switch.sonoff_10006fb002_4"
      - name: "Cesped 4"
        entity_id: "switch.sonoff_10006fc21e_1"
      - name: "Cesped 5"
        entity_id: "switch.sonoff_10006fc21e_2"
      - name: "Huerto"
        entity_id: "switch.sonoff_10006fb002_1"
      - name: "Plantas"
        entity_id: "switch.sonoff_10006fc21e_3"
    sequences:
      - name: "Mañana"
        delay: "00:00:03"
        schedules:
          - name: "Summer - Mañana"
            time: "11:00"
            weekday: [mon, tue, wed, thu, fri, sat, sun]
            month: [jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec]
        zones:
          - zone_id: 1
            duration: "00:10"
          - zone_id: 2
            duration: "00:10"
          - zone_id: 3
            duration: "00:10"
          - zone_id: 4
            duration: "00:10"
          - zone_id: 5
            duration: "00:10"
          - zone_id: 6
            duration: "00:10"
          - zone_id: 7
            duration: "00:15"

Nothing appears into the logs. I have attached  HA processor use chart covering 12-16 of April and where 4 peaks appears at the time the integration start to work until it finish.

## Describe the bug
CPU utlization goes up from 10-12% up to 40-42% when the irrigation kick off. It makes whole HA fairly unresponsive.

## Debug log
![Irrigation_Unlimited](https://user-images.githubusercontent.com/47034221/232307973-9f438021-bb15-4a10-9262-a782710c713e.png)

**Comment by rgc99** [comment]
The `refresh_interval` is set to 1. This means the binary sensors (controller & zone) will be refreshed every second along with recorder. Unless you really want to watch the count down timers then I might suggest a higher value. You should see the CPU utilisation drop as you increase the `refresh_interval`.

**Comment by barto64** [comment]
Thanks for the quick turnaround. I changed it to 5sec and CPU usage dropped from 40% to 30%, so i have now set it up on 15sec.
