### ISSUE TITLE
Adjust Time: reset error

### ISSUE THREAD

**Issue by Bart39** [rgc99/irrigation_unlimited#11]
**Describe the bug**
Calling the adjust time service with reset fails with error:
"Must contain one of actual, percentage, increase, decrease"

**To Reproduce**
1. using developer tools run the following service parameters
2. `service: irrigation_unlimited.adjust_time
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  reset: ''`

**Expected behavior**
run times for specified entity are reset to the schedule defaults

**Additional context**
cv.has_at_least_one_key(CONF_ACTUAL, CONF_PERCENTAGE, CONF_INCREASE, CONF_DECREASE)
this should also contain CONF_RESET

**Comment by rgc99** [comment]
Yep, broken. Suggested workaround is to use percentage = 100 or increase/decrease = '00:00'.

**Comment by rgc99** [comment]
Fix now included in release [2021.5.7](https://github.com/rgc99/irrigation_unlimited/releases/tag/2021.5.7)
