### ISSUE TITLE
[FR] adjust start time/schedule

### ISSUE THREAD

**Issue by bulburDE** [rgc99/irrigation_unlimited#110]
**Is your feature request related to a problem? Please describe.**
I am trying to smartly automate the irrigation for which this integration is really helpful. Using HAsmartirrigation I am adjusting the run time each day. But I would also like to change the time when it runs dynamically. E.g. to run when nobody is home, or the sun is (not) shining.

**Describe the solution you'd like**
either a separate service or an addition to `adjust_time` (since the name indicates that it is possible) to adjust the `schedule.time` attribute. A separate service could be called `adjust_schedule` and also allow to change `weekday`, `day`, `month` and 'anchor`.
It would be nice if not only an absolute time could be set but also a relative time to postpone it. If I notice that it is a bad time for the irrigation to start (e.g. because someone is on the lawn) I could press a button/ call the service to delay the schedule by an hour.

This raises the question if such an adjustment should only be applied to the next schedule or all.

**Describe alternatives you've considered**
Of course I could do that using the manual run service, but then the `duration` and `time` attributes of the zones and sequence wouldn't be useful. I had to rebuilt them with helpers to show them in the frontend.

**Comment by rgc99** [comment]
This request has been around for some time see #8. The good news it is under way with most of the coding for stage 1 done. You can adjust _all_ aspects of a schedule. The first stage is to get the service call operating. The second is to be able to restore after a restart.

Stay tuned.

**Comment by bulburDE** [comment]
Since the issue is stale for a while it is a pleasant surprise that you are working on that feature. I will close this issue in favour of the other one.
I've read through the community thread and a lot of issues here and it is really amazing that you are still developing this integration and most of all the support you've given. Thank you very much!
