### ISSUE TITLE
Does not switch off valve when reloading config

### ISSUE THREAD

**Issue by gaaf** [rgc99/irrigation_unlimited#112]
**Describe the bug**
If I reload the config via the developer tools while a zone is active, afterwards the irrigation card shows all zones off, but the valve switch is still on.

**To Reproduce**
1. Reload config while a zone is active
2. Observer that the zone is inactive now, but the valve is still switched on

**Expected behavior**
I would expect either:
1) The zone keeps its status over a reload, and thus following the valve switch
or
2) The valve is switched off if the zone isn't active anymore due to the reload.

Version 5c63d4b6e5

**Comment by rgc99** [comment]
This is fixed in the current release.
