### ISSUE TITLE
Add overlap seconds (negative delay) between zones in the schedule

### ISSUE THREAD

**Issue by w32-blaster** [rgc99/irrigation_unlimited#113]
**Is your feature request related to a problem? Please describe.**
When irrigating from own water source, a pump is used. Starting and stopping pumps happen on pressure loss. 
When closing one zone and opening another zone, even with zero delay, there is a small gap between two zones. Ideally from the pump's point of view it is better and healthier to keep it running. The easiest to achieve this is to start the next zone before the actual finishes. 

**Describe the solution you'd like**
There are two options I thought may be useful for this: 
1. Use the delay parameter but support negative value. 
2. Add new parameter overlap which would be another time value in seconds. delay and overlap could not be specified at the same time

**Comment by rgc99** [comment]
A similar situation came up a while ago in relation to the controller to prevent hammering, see issue #73. Turned out to be fairly straight forward enough. We will see I guess.

**Comment by w32-blaster** [comment]
I think that solves a different problem. Or I may misunderstand how that works. I don't control the pump directly from this automation. It starts automatically when there is a pressure loss.

**Comment by rgc99** [comment]
I meant that to allow negative values on the controller level was fairly easy. Seems just relaxing the delay parameters to allow negatives appears to work.

**Comment by rgc99** [comment]
This is now available in the latest release.
