### ISSUE TITLE
Reloading configuration enables controller

### ISSUE THREAD

**Issue by Kolia56** [rgc99/irrigation_unlimited#119]
When reloading Irrigation unlimited, the controller is enabled even if it was disabled before that.
Running Irrigation unlimited 2023.6.1

**Comment by luixal** [comment]
I can confirm this is happening. At least when you call the `reload` service.

This can be a huge problem if it also happens when restarting HA... will check that out in a while.

**Comment by rgc99** [comment]
Restarting HA seems fine. The `reload` is not so kind to enabled and adjustments. The fixes are now in the repository along with tests. A note of caution when using `enabled` in the config as it will take precedence over the existing status if present. In this case it would be better to omit and rely on the service call.

**Comment by SuperMaximus1984** [comment]
Configuration reload by `Irrigation Unlimited: Reload ` doesn't do anything at all. Unless HA is restarted, the new configuration from `config.yaml` would never be applied. @rgc99, please fix, otherwise it's unwise to restart the whole system for the sake of 1 integration.

**Comment by Kolia56** [comment]
> Configuration reload by `Irrigation Unlimited: Reload ` doesn't do anything at all. Unless HA is restarted, the new configuration from `config.yaml` would never be applied. @rgc99, please fix, otherwise it's unwise to restart the whole system for the sake of 1 integration.

On my side, using the manual reload (in the UI), not using the service that I have not tested, does reload the configuration and enables the controller despite the fact it was disabled before it. I confirm as well that restarting HA does not enable controller.

**Comment by rgc99** [comment]
Has anyone had a chance to install from the repository and check if this is fixed?

**Comment by Kolia56** [comment]
Thank you. I just checked, Controller disabled: calling service or using UI does not enable controller anymore. Restarting HA does not either (even if it was the case before but good to check there is no regression).
