### ISSUE TITLE
Not an Issue - Hardware question

### ISSUE THREAD

**Issue by Backslashh** [rgc99/irrigation_unlimited#12]
Hi,
Thanks for creating this integration!
Just wanted to know what hardware you are using for this?

I too am in Australia and looking to start a smart sprinkler project but not sure on what hardware I need to work with this integration. 
I was thinking an ESP8266 with a 4-channel relay board attached to 4 solenoids to give me 4 "zones". Ideally I'd pull this together with MQTT.

Just wanting to see what you were doing hardware wise.

**Comment by patricf** [comment]
This is how I did it.
I hade a bunch of Shelly1 laying around the house so I used them with Hunter PGV valves, one valve and one Shelly per zone (4 in  total). I then bought a 24V AC transformer and connected the valves together with the Shelly1 "I" and "O" terminals and then with Home Assistant using MQTT. Then all I had to do was to setup this integration and I was all set.
There are numerous ways, and better ways I guess, to doing this. I just used what I had at home.

**Comment by Stan-Gobien** [comment]
I use a solenoid on mains with a zigbee smart plug

**Comment by rgc99** [comment]
Hi William,

The short answer is you can use any hardware that presents itself as a switch in HA.

Not known for taking the easy path, I am establishing a zigbee network. The grand plan is to run a blueline poly and 24V feed around the perimeter of the property so I can branch off where ever and whenever I need. My garden design has a regular habit of changing! The idea behind this is I can run both irrigation and lighting off the same feed. Problem is lighting is DC and most irrigation valves are AC. Either I rectify AC or find DC valves which are not common or cheap. However, I found https://valvesdirect.net in SA who have a build your own valve, good price and aussie made. Find them on ebay https://www.ebay.com.au/itm/223464143442

The big problem, and I hope someone reading this thread will prove me wrong, is finding a suitable low voltage zigbee relay. Thought there would be lots to choose from but most are 240VAC. Plenty of 12/24V controllers for strip lights but are not suitable. Found this https://vestaaustralia.com.au/product/zigbee-relay-controller but expensive at $60 each. Recently found https://www.aliexpress.com/item/1005002358919462.html and awaiting delivery (they also have a 2 and 4 channel version). Finally, I am concerned about the relay turning on and for whatever reason (HA melt down etc.) the off signal gets lost. I have put in a hardware dead-man switch to limit the maximum run time using https://www.aliexpress.com/item/33014830389.html.

Good luck.

**Comment by Backslashh** [comment]
Ah nice idea!
Are you planning on putting different firmware on that aliexpress relay? let me know how that goes because I might go down that route.
Otherwise I'm looking to build an ESPhome based controller with an ESP8266 and a relay board. Ideally the schedule will be defined and scheduled with Irrigation Unlimited and (in case of HA meltdown) a dead man switch type of software shutoff in the ESPhome configuration. That way if HA melts down, the controller itself will close the relay if it's been open for too long.

**Comment by rgc99** [comment]
I don't have the skill set or resources to modify the firmware. Be great and I wouldn't need the dead man switch, just build it into the firmware.

There is no UI but you can adjust the watering times, manual runs, turn on/off zones via service calls. These can all be done with buttons on the frontend. The idea is once the yaml is setup the day to day operation can be done from the UI or better yet automated completely.

**Comment by rgc99** [comment]
The zigbee relays arrived and connected to HA without problem. The only thing is they appeared in the light domain rather than the switch domain. The main chip is a CC2530F256. It does operate as a router.

**Comment by rgc99** [comment]
I will close this issue off but feel free to continue any discussion in the [community forum](https://community.home-assistant.io/t/irrigation-unlimited-integration/325468/27)

**Comment by SgtBatten** [comment]
> Not known for taking the easy path, I am establishing a zigbee network. The grand plan is to run a blueline poly and 24V feed around the perimeter of the property so I can branch off where ever and whenever I need. 

Hi, so your hardware setup is to have a ZigBee relay at the branch where each solenoid is? How do you weather seal these?

I have a good location in my yard (under my deck) for a 4 or 8ch relay and am trying to work out the system design. 

I assume the I need to run 24v wiring from each relay output to the individual solonoids? So most people who go this route have lots of underground wiring to achieve their irrigation system?
What kind of wires and do you put them in conduit normally? Only have a current need for 2 zones and maybe a third for lawn popup sprinklers.

**Comment by rgc99** [comment]
I thought this might benefit other users so I have posted a write up on the community forum [here](https://community.home-assistant.io/t/irrigation-unlimited-integration/325468/152?u=rgc99)

As this ticket is closed please feel free to post on the Home Assistant Community site.
