### ISSUE TITLE
Sequence not firing

### ISSUE THREAD

**Issue by plefneski** [rgc99/irrigation_unlimited#135]
I have been trying to get this to work for days now and I am not sure where to look next. I have a sequence that is not firing at it's designated time or manually. I have tried restarting homeassistant, running the reload service, running the load schedule service, reloading the integration in HACS, deleting and adding the integration back again, and changing the yaml configuration. I duplicated the sequence in the yaml as you can see below and the second occurrence will fire manually but still not at the designated time. The first still does not run either way.   

I am using version 2023.08.00

irrigation_unlimited:
  granularity: 1
  refresh_interval: 5
  controllers:
    - name: "Outside Sprinkler"
      zones:
        - name: "Back Yard Lawn"
          entity_id: "switch.outside_irrigation_back_lawn"
          check_back:
            delay: 20
            retries: 4
        - name: "Back Yard Fence"
          entity_id: "switch.outside_irrigation_back_fence"
          check_back:
            delay: 20
            retries: 4
        - name: "Back Yard Garden"
          entity_id: "switch.outside_irrigation_back_garden"
          check_back:
            delay: 20
            retries: 4
        - name: "Front Lawn"
          entity_id: "switch.outside_irrigation_front_lawn"
          check_back:
            delay: 20
            retries: 4
      sequences:
        - name: "Seq 1"
          schedules:
            - name: "Sch 1"
              time: "21:00"
          zones:
            - zone_id: 1
              duration: "00:07:00"
            - zone_id: 2
              duration: "00:06:00"
            - zone_id: 3
              duration: "00:10:00"
            - zone_id: 4
              duration: "00:06:00"
        - name: "Seq 2"
          schedules:
            - name: "Sch 2"
              time: "21:00"
          zones:
            - zone_id: 1
              duration: "00:07:00"
            - zone_id: 2
              duration: "00:06:00"
            - zone_id: 3
              duration: "00:10:00"
            - zone_id: 4
              duration: "00:06:00"

I know that an event is not being created because I added the persistent notification automation and I only get a notification on the manual run of the second sequence.

I'm not sure what logs to include.

**Comment by rgc99** [comment]
When posting the configuration.yaml or log files please use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks). Without this the data is squished to the left hand margin. This is particularly important with the configuration.yaml file as the language is very sensitive to indentation. The configuration is not useful without these backticks and will need to be posted again.

Looking at the log file it seems sequence 1 is disabled. The individual zones within the sequence get enabled but not the sequence itself.
```
2023-08-17 11:00:49.086 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-08-17 11:00:49] service: disable, controller: 1, zone: 0, data: {"sequence_id": 1}
```
Try enabling sequence 1. Note a restart will not do it as the state is restored.

**Comment by plefneski** [comment]
Yes that was it. It work fine now. Thanks.
