### ISSUE TITLE
Typo in 5.9 documentation regarding Clock.

### ISSUE THREAD

**Issue by evercape** [rgc99/irrigation_unlimited#144]
**Describe the bug**
[Heading 5.9](https://github.com/rgc99/irrigation_unlimited#59-clock-object) has a typo - twice the word "entries" has been written incorrectly. 

**Expected behavior**
should be: <!DOCTYPE html>

max_log_entries | number | 50 | Set the number of entries in the tick log history
-- | -- | -- | --

**Screenshots**
![rgc99_irrigation_unlimited__♒Irrigation_controller_for_Home_Assistant](https://github.com/rgc99/irrigation_unlimited/assets/4627761/ab47873c-d6da-4ca9-acf7-660bfbb1ca8a)

The actual expected YAML object is correct, ie "max_log_entries"

**Comment by rgc99** [comment]
Many thanks for your feedback.
