### ISSUE TITLE
`from`/`until` field handling does not match documentation

### ISSUE THREAD

**Issue by tjasko** [rgc99/irrigation_unlimited#149]
**Describe the bug**
The `from`/`until` fields on the schema(s) are documented to take in dates under the `mmm dd` format, see the relevant docs below:
https://github.com/rgc99/irrigation_unlimited/blob/409d91a80a70e6f6e97d0a8e739b0051e1f1d472/README.md?plain=1#L293-L296

However, the actual implementation expects the `dd mmm` format, see the relevant code below:
https://github.com/rgc99/irrigation_unlimited/blob/409d91a80a70e6f6e97d0a8e739b0051e1f1d472/custom_components/irrigation_unlimited/schema.py#L101-L105

**To Reproduce**
1. Attempt to create a schedule using the expected format, e.g:
   ```yaml
    - time: "10:15"
      weekday: [mon, wed, fri]
      from: "Oct 01"
      until: "Oct 15"
   ```
2. Notice the config will not pass validation:
    ```
    Cannot quick reload all YAML configurations because the configuration is not valid: Invalid config for [irrigation_unlimited]: not a valid value for dictionary value @ data['irrigation_unlimited']['controllers'][0]['sequences'][0]['schedules'][0]['from']. Got None. (See /config/configuration.yaml, line 130).
    ``` 

**Expected behavior**
The documentation matches the actual implementation.

**Additional context**
There'd likely be two possible outcomes of this issue:
1. Update the documentation to match the `dd mmm` format (which wouldn't break users like myself who took a look at the code).
2. Update the code itself to parse the dates in `mmm dd` format.

I figured to open up an issue to come to a resolution, so that others don't run into this in the future. Either way personally works for me. ISO-8601 [prefers the month following the day format](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates), so perhaps that'd be nicer for most users.

**Comment by rgc99** [comment]
Thank you for reporting this. The documentation has been updated.

**Comment by tjasko** [comment]
Baller, thanks!
