### ISSUE TITLE
Documentation: More object shall be replaced by User object

### ISSUE THREAD

**Issue by Kolia56** [rgc99/irrigation_unlimited#150]
Among others, thank you for the addition of the User object. However in the documentation (Controller, All Zone and Zone) this object is named More instead of User and the corresponding link is broken.

Nicolas

## Version of the custom_component
2023.11.0

**Comment by evercape** [comment]
Thanks @Kolia56 I think that was my bad. Initially I suggested a `more:` object, and Robert changed it to `user:` which is more appropriate. When writing the documentation to this, this slipped my mind.

Have updated and created [pull reques](https://github.com/rgc99/irrigation_unlimited/pull/151)t.

Thanks for spotting.

**Comment by Kolia56** [comment]
Thanks for your quick feedback.
Nicolas
