### ISSUE TITLE
How to add soil moisture sensor???

### ISSUE THREAD

**Issue by icssdan** [rgc99/irrigation_unlimited#16]
Hello, I want to add a soil moisture sensor, but I don't know how I could integrate it, in the sense that: when it rains and the soil moisture is >40%, the sprinklers don't start. The soil moisture sensor I made an ESP32 and a probe.
Best regards,

**Comment by rgc99** [comment]
Cool, I assume you have the sensor working in Home Assistant, do you have any details? Go to Developer Tools -> States and select the entity, it should show the State and list of State attributes. Please post them here.

What did you have in mind? At 40% the system is off but what about 20%? Should they run for half the time? Did you want a sliding scale of simply on/off when it hits 40%?

**Comment by icssdan** [comment]
Helooo my friend.The percentage of 40% I gave just as an example :))
![screenshot](https://user-images.githubusercontent.com/76975514/119782753-3d425180-bed5-11eb-8189-34debf80dd88.png)
Below I attach my configuration.Now the humidity is 60%, but when I reach 70 (for example) the system does not start.thank you in advance 

**irrigation_unlimited:
  controllers:
    - name: "MainValve"
      entity_id: "switch.sonoff_mainvalve"
      enabled: true
      preamble: '00:01'
      postamble: '00:01'
      zones:
        - name: "Yard1"
          entity_id: "switch.irig_valve1"
          enabled: true
        - name: "Yard2"
          entity_id: "switch.irig_valve2"
          enabled: true
        - name: "Yard3"
          entity_id: "switch.irig_valve3"
          enabled: true
        - name: "Yard4"
          entity_id: "switch.irig_valve4"
          enabled: true
      sequences:
        - delay: "00:01"
          schedules:
#######PROGRAM: 1
            - name: Program1
              time: "08:00"
            - name: Program2
              time: "18:00"
          zones:
            - zone_id: 1
              duration: "00:05"
            - zone_id: 2
              duration: "00:05"
            - zone_id: 3
              duration: "00:10"
            - zone_id: 4
              duration: "00:10"**

**Comment by rgc99** [comment]
The bit that ties your sensor to Irrigation Unlimited is an [automation](https://www.home-assistant.io/docs/automation). When the sensor changes a service call is made to adjust the run time. There are a couple of options shown here, tweak to suit your needs. Happy irrigating.

```yaml
automation:
  - alias: Irrigation Unlimited Adjustment
    trigger:
      platform: state
      entity_id:
        - sensor.yard1_humidity
    action:
      service: irrigation_unlimited.adjust_time
      data:
        entity_id: binary_sensor.irrigation_unlimited_c1_m
        percentage: >
          {# Threshold variable #}
          {% set threshold = 40 %}

          {# Sensor data #}
          {% set humidity = states('sensor.yard1_humidity') | float %}

          {% if humidity < threshold %}
            {# Option 1 - A linear sliding scale #}
            {% set multiplier = 1 - (humidity / threshold) %}
            {# Option 2 - On or Off #}
            {% set multiplier = 1.0 %}
          {% else %}
            {% set multiplier = 0.0 %} {# It's too wet #}
          {% endif %}

          {# Return multiplier as a percentage #}
          {{ (multiplier * 100) | round(0) }}
```

**Comment by rgc99** [comment]
Example now included in documentation.
