### ISSUE TITLE
Support valve entities available since 2024.1

### ISSUE THREAD

**Issue by Joao-Sousa-71** [rgc99/irrigation_unlimited#161]
**Is your feature request related to a problem? Please describe.**
My irrigation valves expose valve entities instead of switches and more and more solenoids will implement the domain valve.

**Describe the solution you'd like**
The integration should support the valve entities as per the following:

https://www.home-assistant.io/integrations/valve/#valve-control-services

**Describe alternatives you've considered**
One workaround for now is a switch created in HA that call scripts to open and close the valves.

**Additional context**
Nevertheless this integration is awesome.

**Comment by Kolia56** [comment]
Why not, but as of now it does not seem that valves entities can be created using [templates ](https://www.home-assistant.io/integrations/template/) which is needed as far as I'm concerned

**Comment by Joao-Sousa-71** [comment]
I've just install the latest version and so far so good. Have a a schedule by the end of the day and will check how it goes but looks promising. Thank you!

**Comment by Joao-Sousa-71** [comment]
It works great! Thank you @rgc99
