### ISSUE TITLE
future_span does not seem to work when changing schedule over the next few days that lie within future_span

### ISSUE THREAD

**Issue by evercape** [rgc99/irrigation_unlimited#162]
**Describe the bug**
`future_span=6` means that the run queue looks ahead 6 days. I have set this on `all_zones_config` so it should apply everywhere. 

**To Reproduce**
```
irrigation_unlimited:
controllers:
  - name: Lawn Areas
	all_zones_config:
	  show:
		timeline: true
		config: true
	  future_span: 6
	zones:
	  - 
	  -
	  -
	sequences:
	  - name: "Lawn: Main House"
		duration: "00:30"
		schedules:
		  - name: "Summer MH"
			time: "04:00"
			weekday: [mon, tue, wed, thu, fri, sat, sun]
			month: [oct, nov, dec, jan, feb, mar, apr]
		  - name: "Winter MH"
			time: "08:00"
			#day:
			#  every_n_days: 3
			#  start_n_days: 2024-05-01
			weekday: [mon, wed, fri]
			month: [may, jun, jul, aug, sep]
		zones:
		  - zone_id: 1
		  - zone_id: 2
		  - zone_id: 3
```
	  

**Expected behavior**
I would expect the companion card to show the change of schedule. 

**Screenshots**
This screenshot shows that the schedules does not go ahead
![Martin_Testing_–_Home_Assistant](https://github.com/rgc99/irrigation_unlimited/assets/4627761/76040520-c5e5-4577-b510-c29f3c943e97)

Thanks
Martin

**Comment by rgc99** [comment]
Not sure I understand this completely. Is it the transition from the "Summer MH" schedule to the "Winter MH" schedule? What is the current date? Tuesday was the 30/4 - the last Summer MH then the next should be 1/5 - the first Winter MH schedule.

**Comment by evercape** [comment]
Hi Robert,
thanks - yes its the transition. the date I did this screenshot was on April 29. I would have exited the card to show the 29 April, 30 April, 1 May, ... (new schedule) when clicking on the zone. Is that not how it's supposed to work with `future_span: 6` ?

**Comment by rgc99** [comment]
What is shown comes from the `timeline` attribute on the zone entity but it is filtered to only display history items. Extending the `future_span` won't affect what you see. If you are wondering about removing the filter then yes it would probably show what you want (possibly alter the icon to distinguish future and history items).

The card only displays the next upcoming schedule from the `next_start`, `next_schedule`, `next_name` attributes.

**Comment by evercape** [comment]
Thanks, that resolves that.
