### ISSUE TITLE
First zone in schedule is not scheduled

### ISSUE THREAD

**Issue by sdelmas** [rgc99/irrigation_unlimited#172]
**Describe the bug**
First zone "Front NW" is not scheduled. I sure hope I am not doing something stupid here... if I do, my apologies. I swapped the first two zones, and at that point "Front E" is not scheduled. This leads me to believe that this not about the zone config.

**To Reproduce**
Configuration:
`
controllers:
  - name: "Outside"
    all_zones_config:
      show:
        timeline: true
        config: true
    zones:
      - name: "Front NW"
        entity_id: "switch.rachio_sprinkler_front_nw_lawn"
      - name: "Front E"
        entity_id: "switch.rachio_sprinkler_front_east_lawn"
      - name: "Front S"
        entity_id: "switch.rachio_sprinkler_front_south_lawn"
      - name: "Back N"
        entity_id: "switch.rachio_sprinkler_back_north_lawn"
      - name: "Back S"
        entity_id: "switch.rachio_sprinkler_back_south_lawn"
      - name: "Unknown"
        entity_id: "switch.rachio_sprinkler_unknown"
      - name: "Flowers, Trees; Shrubs"
        entity_id: "switch.rachio_sprinkler_back_flower_bed_back_trees_shrubs"
      - name: "S Drive; Islands"
        entity_id: "switch.rachio_sprinkler_front_islands_s_driveway"
      - name: "N Drive; Shrubs"
        entity_id: "switch.rachio_sprinkler_n_driveway_front_shrubs"
      - name: "S Tree Line"
        entity_id: "switch.b_hyve_sprinkler_zone_1_s_tree_line"
      - name: "N Tree Line"
        entity_id: "switch.b_hyve_sprinkler_zone_2_n_tree_line"
      - name: "Unknown"
        entity_id: "switch.b_hyve_sprinkler_zone_3"
      - name: "Shop Front"
        entity_id: "switch.b_hyve_sprinkler_zone_4_shop_front"
    sequences:
      - name: "Spring and Autumn Sprinkler"
        duration: "00:05"
        repeat: 2
        schedules:
          - time:
              sun: "sunrise"
              before: "00:05"
            weekday: [mon, wed, fri]
            month: [mar, apr, may, sep, oct, nov]
            anchor: finish
        zones:
          - zone_id: 1
          - zone_id: 2
          - zone_id: 3
          - zone_id: 4
          - zone_id: 5
      - name: "Spring and Autumn Drip"
        duration: "00:05"
        repeat: 2
        schedules:
          - time:
              sun: "sunset"
              after: "01:00"
            weekday: [mon, wed, fri]
            month: [mar, apr, may, sep, oct, nov]
            anchor: start
        zones:
          - zone_id: 8
          - zone_id: 9
          - zone_id: 10
          - zone_id: 11
          - zone_id: 13
          - zone_id: 7
      - name: "Summer Sprinkler"
        duration: "00:05"
        repeat: 3
        schedules:
          - time:
              sun: "sunrise"
              before: "00:05"
            weekday: [mon, wed, fri]
            month: [jun, jul, aug]
            anchor: finish
        zones:
          - zone_id: 1
          - zone_id: 2
          - zone_id: 3
          - zone_id: 4
          - zone_id: 5
      - name: "Summer Drip"
        duration: "00:05"
        repeat: 3
        schedules:
          - time:
              sun: "sunset"
              after: "01:00"
            weekday: [mon, wed, fri]
            month: [jun, jul, aug]
            anchor: start
        zones:
          - zone_id: 8
          - zone_id: 9
          - zone_id: 10
          - zone_id: 11
          - zone_id: 13
          - zone_id: 7
      - name: "Winter Sprinkler"
        duration: "00:05"
        repeat: 1
        schedules:
          - time:
              sun: "sunrise"
              before: "00:05"
            weekday: [mon, wed, fri]
            month: [dec, jan, feb]
            anchor: finish
        zones:
          - zone_id: 1
          - zone_id: 2
          - zone_id: 3
          - zone_id: 4
          - zone_id: 5
      - name: "Winter Drip"
        duration: "00:05"
        repeat: 1
        schedules:
          - time:
              sun: "sunset"
              after: "01:00"
            weekday: [mon, wed, fri]
            month: [dec, jan, feb]
            anchor: start
        zones:
          - zone_id: 8
          - zone_id: 9
          - zone_id: 10
          - zone_id: 11
          - zone_id: 13
          - zone_id: 7
`

**Expected behavior**
Zone 1 should be scheduled (along with all the others).

**Screenshots**
Notice that "Front NW" is not scheduled.

<img width="412" alt="Screenshot 2024-07-24 at 6 06 30 PM" src="https://github.com/user-attachments/assets/c2e21bc5-1a96-466c-b7b0-a9f68c98f2db">

**Irrigation Unlimited log file**
Nothing in the log history... do I need to turn on debugging somewhere, or is this because there hasn't happened anything (this is right after a restart of HA).

```text
2024-07-24 18:16:25.264 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigation_unlimited which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Desktop (please complete the following information):**
 - OS: Mac OS (Sonoma 14.5)
 - Browser Chrome
 - Version 126.0.6478.183
 - Using the Home Assistant App

**Smartphone (please complete the following information):**
 - Device: N/A

**Additional context**

**Comment by sdelmas** [comment]
Also not sure why zone 6 is cancelled... I don't recall doing that. That one I don't care about, just weird. Is there a way to reset all state for the integration without uninstalling?

**Comment by rgc99** [comment]
My guess is that zone 1 in the "Summer Sprinkler" sequence is disabled. There should be more log entries, search for 'irrigation_unlimited'. It should show the status or post a screen shot of the sequence expanded. If it is disabled then enable it from the dropdown  menu on the right.

Also it looks like zone 6 is disabled. Enable it from the dropdown menu to the right.

**Comment by sdelmas** [comment]
Ok... after the manual run, the zone is now listed as scheduled. So not sure what caused the initial issue, and probably not likely to be debuggable. I will monitor and reopen if there is a recurrence. Do let me know if there is anything else I can do for this issue, or in general.

**Comment by sdelmas** [comment]
Ok, something is definitively off still. The zone ran much longer than the others (although the setup for the time is the same as all other sprinkler zones) and the UI shows this for the duration.

<img width="412" alt="Screenshot 2024-07-26 at 8 35 24 AM" src="https://github.com/user-attachments/assets/5592c224-4c77-4af9-8856-253f3bb52686">

**Comment by rgc99** [comment]
There is an adjustment in play for zone 1. It is set to 6 minutes and 44 seconds no matter what. Did you mean to do that? The adjustment can also be set to 0 which may have been the reason zone 1 was not being scheduled before. To clear/reset an adjustment, use the drop down menu on the right but leave the box empty.

If you go into Settings -> System -> Logs and search for `irrigation_unlimited` (note the underscore between the words) and press "LOAD FULL LOGS". Do you have some automation making adjustments?

**Comment by sdelmas** [comment]
Aha! Cool... that explains it. I was experimenting with the "Smart Irrigation" integration. Still learning how all this plays together. I think this explains all the issues... thank you so much!
