### ISSUE TITLE
Manual vs. Automatic recognition

### ISSUE THREAD

**Issue by danielegger1** [rgc99/irrigation_unlimited#175]
Hello

I do have issues with my automations, as I cannot differentiate between Manual or Automatic irrigation.
Is there any way I can know the type of the irrigation, if it was activated manually or automatically?
Based on this, I would like to change the behavior.

**Comment by rgc99** [comment]
Yes, the `current_schedule` attribute on the zone/sequence will be 0 if it is a manual run otherwise it indicates which schedule triggered the run.

**Comment by danielegger1** [comment]
I tried this and it does not react, I can see the value changes to 0 as you say, but I may do something wrong at the Automation
  - condition: state 
    entity_id: switch.irrigation_control_valve_6
    attribute: current_schedule
    state: "0"

**Comment by danielegger1** [comment]
I got it, thanks a lot! Solution:

condition:
  - condition: state
    entity_id: binary_sensor.irrigation_unlimited_c1_z6
    attribute: current_schedule
    state: 0

**Comment by danielegger1** [comment]
Working
