### ISSUE TITLE
Using irrigation_unlimited.shim_enable/disable for sequences

### ISSUE THREAD

**Issue by PaPa1ya** [rgc99/irrigation_unlimited#176]
**Is your feature request related to a problem? Please describe.**
I like to use the cards provided in the examples to manage the zones, but I would also like to manage the sequences using the same irrigation_unlimited.shim_disable/enable

**Describe the solution you'd like**
I would like irrigation_unlimited.shim_disable to be able to accept input_select.irrigation_unlimited_sequences to disable sequences and irrigation_unlimited.shim_enable to enable

**Describe alternatives you've considered**
In fact, I have a need to disable schedules and not sequences, maybe there is some way through the interface?

**Additional context**
I'm not sure if this is a bug, most likely this feature just wasn't implemented

**Comment by rgc99** [comment]
You can update an existing schedule the [`load_schedule`](https://github.com/rgc99/irrigation_unlimited?tab=readme-ov-file#77-service-load_schedule) service (including enable/disable). One proviso is that changes made through this service call are NOT saved and will revert to the configuration.yaml if the integration is reloaded, HA is restarted etc.
