### ISSUE TITLE
controller_id how to number controllers

### ISSUE THREAD

**Issue by paulbalinnel** [rgc99/irrigation_unlimited#177]
Description : when adding a new controller the newest controller gets auto assigned to id : 1, which causes all other controller yaml in Lovelace to shift on 1, example binary_sensor.irrigation_unlimited_c7_z1 becomes …_c8_z1

![Screenshot 2024-08-11 at 16 40 21](https://github.com/user-attachments/assets/73d05932-e4eb-4fd0-9aae-b9616a2ee8eb)

I want to add a new controller number 10, however
controllers:
      - name: Lahana
        controller_id: ’10’
        enabled: true      
        all_zones_config:

has not worked

pls will you give me some advice on how to set the controller id to a specific number?

**Comment by rgc99** [comment]
To rename the entities you need to set `rename_entities` in the [configuration](https://github.com/rgc99/irrigation_unlimited?tab=readme-ov-file#5-configuration) to `true`.
