### ISSUE TITLE
state_changes_during_period was called from irrigation_unlimited, this is a deprecated function

### ISSUE THREAD

**Issue by kotana** [rgc99/irrigation_unlimited#18]
Logger: homeassistant.components.history
Source: helpers/deprecation.py:122
Integration: History (documentation, issues)
First occurred: 7:24:50 (9 occurrences)
Last logged: 7:25:10

state_changes_during_period was called from irrigation_unlimited, this is a deprecated function. Use homeassistant.components.recorder.history.state_changes_during_period instead, please report this to the maintainer of irrigation_unlimited

**Comment by rgc99** [comment]
I will get on to this. Please note everything is working fine. What has happened is the Home Assistant developers have decided to move some functionality around and are warning developers to update their code. It is the same code but in a different location. For now they have a redirection but intend to remove it at some future date.
