### ISSUE TITLE
Manual_run error in pyscript file

### ISSUE THREAD

**Issue by jorik12345** [rgc99/irrigation_unlimited#19]
**Describe the bug**
I am getting the following error in my logs:
`Exception in <file.irrigation_unlimited_service_shim.irrigation_unlimited_list_config> line 39: data = json.loads(irrigation_unlimited.coordinator.configuration) ^ AttributeError: 'StateVal' object has no attribute 'configuration'`

My coordinator only has a state of `ok` and `friendly_name` and `icon` as attributes.

**To Reproduce**
1. Install with the minimum configuration
2. Add the pyscript and helpers
3. Restart Home Assistant

**Expected behavior**
Input selects are filled with the correct zones and sequences

**Comment by rgc99** [comment]
You need at least version 2021.6.3 which is currently a pre-release. After installation you should see a ```configuration``` attribute in the coordinator. I will note the requirement in the documentation for future reference.

**Comment by jorik12345** [comment]
Ah, I missed that part! I will upgrade or patiently wait for the release of 2021.6.3.

**Comment by rmeekers** [comment]
I don't know if this is related, but the manual run inputs are not populated (I'm on 2021.6.3)
<img width="479" alt="Screenshot 2021-06-09 at 20 09 56" src="https://user-images.githubusercontent.com/5755308/121406760-d7d37380-c95e-11eb-918e-197f09bb077e.png">

**Comment by rgc99** [comment]
Available in current release.
