### ISSUE TITLE
Adjust runtime of sequence

### ISSUE THREAD

**Issue by Olum-hack** [rgc99/irrigation_unlimited#24]
Thank you for that great tool. I like und use it in my garden a lot.
Over night I adjust the runtime of all zones with the result from HAsmartirrigation. The irrigation starts before the sun comes up. That works greate.

No I would like to add a additional sequence that runs in the afternoon in summer with a fix value. But I can't define the sequence in the adjust_time command.

Is it possible to add a parameter to select the sequence that should be changed?

Or do you have a different idea?

**Comment by rgc99** [comment]
Funny you should mention this as I had been thinking about this feature. As you say, add a sequence_id parameter to the adjust_time service call similar to manual_run. Want to avoid a confusing situation when a sequence adjustment is called and the underlying zone has an adjustment in play. I think the sequence adjustment should override and ignore any zone adjustment.

**Comment by rgc99** [comment]
This feature is now available in the current release. Closing off this issue.
