### ISSUE TITLE
Error in starting component

### ISSUE THREAD

**Issue by febalci** [rgc99/irrigation_unlimited#27]
HA: 2021.4.6
Irrigation Unlimited: 2021.6.15

Having this error and the component is not working. It was working well with previous version:

```
 Unable to prepare setup for platform irrigation_unlimited.binary_sensor: 
Platform not found (cannot import name 'history' from 'homeassistant.components.recorder'
 (/usr/src/homeassistant/homeassistant/components/recorder/__init__.py)). 
```

EDIT: IU 2021.6.3 works fine.

**Comment by rgc99** [comment]
You need to update HA. The developers moved the history component. Previously, IU was logging a deprecated function warning regarding this component so it was updated to follow the latest changes.

**Comment by rgc99** [comment]
Actually, roll back to IU 2021.6.3 and for the next release I will put a in a check for the HA version to load the correct import. I understand there could be reasons why updating HA is not an option.

**Comment by AlfonsPuig** [comment]
Hi, I have upgraded core and supervisor to the last version and the problem is gone

**Comment by febalci** [comment]
Thanks, will continue with 2021.6.3 for now..
