### ISSUE TITLE
Next Schedule

### ISSUE THREAD

**Issue by johnnysmithy852456** [rgc99/irrigation_unlimited#30]
Hi 
Thank you for this great integration to HA
Can I ask when does the Next Schedule update 
For me it's Wednesday today and my next scheduled day to water is Sunday Im using the Seasonal watering config example.

![Screen Shot 2021-07-21 at 2 41 50 pm](https://user-images.githubusercontent.com/60836292/126432261-0f712efd-071e-4277-91b8-012472fe5647.png)

**Comment by rgc99** [comment]
Currently the look ahead (future_span) is hard wired to 3 days. This will be tunable in the next release. The feature was committed on 22-Jun-2021. Next release is due out soon or grab the files from the repository.

**Comment by johnnysmithy852456** [comment]
Ok great thanks
