### ISSUE TITLE
Log book entries  

### ISSUE THREAD

**Issue by johnnysmithy852456** [rgc99/irrigation_unlimited#36]
Hi Robert
Is this normal for the average state to be triggering this often.
Thanks
Nick
![Screen Shot 2021-08-28 at 10 55 59 am](https://user-images.githubusercontent.com/60836292/131201443-b5bb3009-9c2f-4590-98e0-468c1ce6065a.png)

**Comment by rgc99** [comment]
I don't think so. The adjustment is triggered by a change in the average sensor which is triggered by a change in sensor.wupws_temp. So what's going on? If you put this code into Developer Tools->Template->Template editor it will show the last update of the `sensor.wupws_temp` and the sensor created by the average platform.
~~~
wupws_temp: {{ states.sensor.wupws_temp.last_updated }}
Moving average: {{ states.sensor.irrigation_unlimited_temperature_5_day_moving_average.last_updated }}
~~~
Looks like the 5 day moving average sensor has updated yet the input sensor `sensor.wupws_temp` did not. Not sure why it would update when the dependent entities did not. Worth posting a question to https://github.com/Limych/ha-average

The good news is Irrigation Unlimited checks the adjustment request against the current and will ignore if it is the same.

**Comment by johnnysmithy852456** [comment]
Hi thanks for that info. After checking the Template editor I found the temp sensor updating as normal looks like every 1℃ increments defiantly not every 30sec like the average sensor is changing. Ill ask the question over at https://github.com/Limych/ha-average.

**Comment by johnnysmithy852456** [comment]
Ok Limych has replied and it's normal for the average sensor to pole that often.
"If you are not satisfied with this, you can change the refresh rate of the sensor. [https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval](url)

**Comment by rgc99** [comment]
It would be nice if it only updated when something changed but this a polling integration. Can't think of an easy workaround so I will change the `scan_interval` in the examples to say 10 minutes.
