### ISSUE TITLE
Integration setup on start up takes more than 3mins

### ISSUE THREAD

**Issue by drthanwho** [rgc99/irrigation_unlimited#37]
**Describe the bug**
The integration takes a very very long time to start up after a restart. It's halting HA's starting up sequence quite a while. 

**Expected behavior**
Is this integration so so heavy that such long time to startup is normal? (or even acceptable?)

**Screenshots**
![image](https://user-images.githubusercontent.com/22405505/131734284-6ac9bad2-32ed-410d-8ffc-184083d74027.png)

**Comment by johnnysmithy852456** [comment]
Just for your reference my installation takes 1.18sec to setup.
You could check your error logs that might help

**Comment by rgc99** [comment]
Check your history as well. During startup it gets the previous `enabled` state to restore and loads the history data. By default it is stored in the config directory called `home-assistant_v2.db`. Make sure it hasn't grown out of control for some reason and is working properly. Mine takes 1.31 seconds to load.

**Comment by drthanwho** [comment]
what does previous enabled state mean exactly btw? 

I'm not using sqlite but MariaDB and on an SSD so I wouldn't expect that to be an issue. Usually things load pretty fast for history.
On last restart it took 40s which is perhaps a bit longer but at least acceptable compared to 3mins.  I don't see any errors but I'll enable debug for it and see if anything there gives any hints

**Comment by rgc99** [comment]
The `enabled` is an attribute on the controller and zone entities. It is manipulated by the enable/disable/toggle service calls. The attribute is persistent and survives HA restarts. The previous state of this attribute is read from HA and set accordingly during startup. Kind of like how one might attempt restarting watering...

**Comment by rgc99** [comment]
Stale issue.
