### ISSUE TITLE
Manual Run Card

### ISSUE THREAD

**Issue by johnnysmithy852456** [rgc99/irrigation_unlimited#39]
Hi there
Great new features in the new update!
Just noticed the timer entry on the Manual Run card as a am/pm option. Has a home assistant update caused this?
I noticed this before the 2021.9.0 update.
![Screen Shot 2021-09-11 at 6 56 47 pm](https://user-images.githubusercontent.com/60836292/132942488-24a8d3b5-5bc2-4977-b259-e8bfee125539.png)

**Comment by rgc99** [comment]
No not me. It comes from HA in the user profile settings -> Time Format. I had requested at some stage an option to the lovelace input_datetime control to select on an individual basis 12/24h format so it could be used as a duration control. Don't think it got enough support.

**Comment by johnnysmithy852456** [comment]
Ok great I change the format back 24hr and it's back to normal
00:10
Thanks

**Comment by rgc99** [comment]
I will close off this issue. I have posted a new manual run card [here](https://community.home-assistant.io/t/irrigation-unlimited-integration/325468/28?u=rgc99). Please check it out.
