### ISSUE TITLE
WiFi disruption leaves ESP home in intermediate state, no good for irrigation systems

### ISSUE THREAD

**Issue by Bazmundi** [rgc99/irrigation_unlimited#43]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
Using ESPHome with a quad relay board to drive sprinkler system seems a great idea.    However, WiFi disruptions found ESPHome relays in indeterminant states.   When WiFi connection re-established, the ESPHome device had random relays ON and their state was not reflected in the HA end, so you could not detect the error state HA end.   Result, waste of water and depending upon the length of time until you found the error condition, an expensive problem.

## Debug log

```text

Error logs only reflected the loss of comms and then the re-establishment of comms.   Logs did not reflect the disconnect in states.

```

[Description here](https://organicmonkeymotion.wordpress.com/2020/05/02/haesphome-no-good-for-critical-systems/)

Solution was to drop ESPHome as means to drive relays and use a smarter sprinkler node that had minimum and maximum limits on how long a sprinkler ran for, so if there was a drop in comms, the sprinkler would turn off anyway.

https://github.com/Bazmundi/opensprinklette

Still working on auto node registration (uses a herald message on start up and also lwt to report offline condition).   Have dropped hand coded scheduler for hand built HA automations, but may look at how to integrate with either irrigation template or irrigation unlimited now I have "discovered" them - thanks.

**Comment by rgc99** [comment]
Hi Asterion,

This has been discussed https://github.com/rgc99/irrigation_unlimited/issues/12 and further https://github.com/rgc99/irrigation_unlimited/issues/35. No matter what integration you choose or create your own automations there will still be a need for a fail safe at the valve level. I am creating a zigbee network but each relay also has a hardware count down timer or dead man switch to limit the on time. I was contemplating adding a watchdog routine to see if the switches are out of sync and maybe realign them. Might help a bit.

This is an important topic and I like what you are doing to create a robust irrigation valve with safe guards. It would be better served to have this discussion on the community forum https://community.home-assistant.io/t/irrigation-unlimited-integration/325468. I will kick it off.

**Comment by rgc99** [comment]
Continued [here](https://community.home-assistant.io/t/irrigation-unlimited-integration/325468/43)
