### ISSUE TITLE
More of a question then an issue

### ISSUE THREAD

**Issue by Notrial** [rgc99/irrigation_unlimited#6]
Quick rookie question: is there a service call through which I can switch to different schedule for a controller (with 4 lines)?
Or am I thinking in a wrong way :)
Hopefully I don't have to edit config/reboot every time I want to switch schedules, or create separate entities (controllers) for each schedule.
This is my current config. Looking at switching between "3x week" and "every other day "schedules".

https://pastebin.com/4fiPpTM4

Everything else works beautifully. Awesome component. Thanks!

**Comment by rgc99** [comment]
There is no way to enable/disable schedules at present. Not to say it can't be done but I am wondering if there is some other way to accommodate your needs. Do you have a little background on what you are trying to achieve? What is the criteria or conditions behind the need to switch schedules?

**Comment by Notrial** [comment]
OK so this is the general idea. Comes Spring I would like to switch from watering once a week to 3 times a week to 2 and eventually every day approaching the summer. But it's not an ideal scenario. Sometimes it can rain for days and you only need to water once that week etc. It's not a huge deal to change the schedule in config.yaml but that does require unnecessary rebooting of the whole HA instance. Perhaps this could be done through service call (with schedule name parameter)? Then we could create a dropdown in the front end that selects the wanted schedule.

**Comment by rgc99** [comment]
Thanks for the background, it does help to understand the situation. A couple of things here that might help. A schedule can specify the days of the week as you know but can also specify the months of the year (jun, jul, aug). This would help you setup spring, summer and winter schedules for example, have one for each month. You might also want to look at using weather observation data and setup a sensor that makes 'adjust_time' service calls to alter the watering times. There are some samples in the examples folder in the repository. Finally, no need to restart HA after changing the yaml file, go to Configuration ->Server Controls -> YAML configuration and reloading and hit 'RELOAD IRRIGATION UNLIMITED'.

Actually I am not that against the idea of dynamically enabling schedules and for that matter sequences. Might add this down the track.

**Comment by Notrial** [comment]
Yeah I think month config should help fine tune my setup, thanks!
And I had no idea you could reload the integration without rebooting, thanks for that as well.

One suggestion...I think it would be really beneficial to add a few examples of automations with service calls in the documentation, especially for beginners. Maybe even create a custom lovelace control card down the road, where you could fine tune the schedule through front end (i.e. text field where you could enter adjust time percentages). The status card from the example in your documentation (ss below) already works beautifully, but I think it could be perfected with dynamic service calls etc. I know I might be asking too much hehe, but I can see how dabbing into service calls might be difficult for beginners and that would be tremendous help.

![image](https://user-images.githubusercontent.com/36201754/113505233-c5dbeb80-953d-11eb-9805-b71a6e7b5450.png)

**Comment by rgc99** [comment]
Happy to help and thanks for the feedback. A lovelace card for configuration would be great but in the meantime I will look at a card to make some service calls. There is a bit of learning curve with HA but it getting easier and the support from the community is great.
