### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by han-alink** [rgc99/irrigation_unlimited#60]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 15:39:49 (1 occurrences)
Last logged: 15:39:49

Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom component author for irrigation_unlimited using this method at custom_components/irrigation_unlimited/history.py, line 142: data = history.get_significant_states(

**Comment by johnnysmithy852456** [comment]
Ive got this warning too in my HA.

**Comment by rgc99** [comment]
The Home Assistant developers have enhanced some operations and would like other developers to adopt the new procedures. Please be aware this not a bug and everything is working as it should.

This work has been done and the changes are in the repository. They will appear in the next release or now if you want to do a manual install.

For those interested, two attributes `today_total` and `timeline` access history information. The routine is now asynchronous with better caching. It did entail some reworking.

**Comment by johnnysmithy852456** [comment]
Thanks for the update Rob

**Comment by han-alink** [comment]
Thanks for your help,Han
-------- Oorspronkelijk bericht --------Van: Robert Cook ***@***.***> Datum: 23-05-22  04:33  (GMT+01:00) Aan: rgc99/irrigation_unlimited ***@***.***> Cc: han-alink ***@***.***>, Author ***@***.***> Onderwerp: Re: [rgc99/irrigation_unlimited] database issue (Issue #60) 
The Home Assistant developers have enhanced some operations and would like other developers to adopt the new procedures. Please be aware this not a bug and everything is working as it should.
This work has been done and the changes are in the repository. They will appear in the next release or now if you want to do a manual install.
For those interested, two attributes today_total and timeline access history information. The routine is now asynchronous with better caching. It did entail some reworking.
