### ISSUE TITLE
Switch based on seconds

### ISSUE THREAD

**Issue by klassm** [rgc99/irrigation_unlimited#65]
Hey there,

would it be possible to add switching based on seconds? I have some plants that require quite few water. When I adapt the sequence by percentage, 50% of 1 minutes is then just 0. But this is a bit few then ...

For me it would even be enough if this was added just during switching, not even in the yaml itself.

Thanks :-)
Matthias

**Comment by rgc99** [comment]
Lower the `granularity` setting. It is the internal clock and forms the base time units. By default it is 1 minute and all times will be rounded to increments of 60 seconds. Choose a value that is the smallest watering time you require.

**Comment by klassm** [comment]
Thank you so much :-)
