### ISSUE TITLE
manual_stop

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#7]
I think it could be a good idea if you could make a service to manual stop the current irrigation run, either manual or scheduled.

In my system I have a workaround to do it by calling `irrigation_unlimited.disable` and `irrigation_unlimited.enable` in sequence as you can see here: [https://github.com/rgc99/irrigation_unlimited/issues/2](url)

With this service it's easy to make a button to switch on/off manual runs, or to stop the actual scheduled run.

**Comment by rgc99** [comment]
Perhaps a irrigation_unlimited.cancel service to stop any currently running schedule. At present a manual run will cancel any running schedule but there is really no other way except the work around you are using.

**Comment by rgc99** [comment]
This is now addressed in https://github.com/rgc99/irrigation_unlimited/releases/tag/2021.4.13

**Comment by miguelpucela** [comment]
It works perfectly both in controllers and in zones.

Thank you!
