### ISSUE TITLE
Irrigation Unlimited CARD unloaded

### ISSUE THREAD

**Issue by Tiranito** [rgc99/irrigation_unlimited#87]
**Describe the bug**
I have installed Irritagion unlimited from HACS and later lovelace CARD but it does not load

**To Reproduce**
1. Install irrigation unlimited from HACS integrations
2. Restart de system.'
3. Install irrigation unlimited-card from HACS Interfaces
4. Restart de system.'
5. irrigation unlimited-card is unloaded. The message that I attach in the image appears

**Expected behavior**
I can't create custom lovelace, because irrigation-unlimited-card is not loaded
I can't uninstall it and reinstall it either, I have deleted the www/customs folder but the error continues

**Screenshots**
Attached screens

**Versions**
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest
HACS 
   Versión de la integración:  1.27.1
   Versión del front-end:  20220825160758
Irrigation unlimited: lastest

**Additional context**
 
![irrigation unlimited 1](https://user-images.githubusercontent.com/13832250/188096915-e60f554e-1505-4bfe-9133-6e9ca13af077.jpg)
![irrigation unlimited 2](https://user-images.githubusercontent.com/13832250/188096918-ac62606c-a90d-47d1-891c-bdc7c05687d2.jpg)

**Comment by rgc99** [comment]
Make sure you clear out the browser cache. If you have removed the www/community/irrigation-unlimited folder and it still loads then this is the most likely cause.

**Comment by rgc99** [comment]
Stale issue
