### ISSUE TITLE
Irrigation companion card: manual run needs to have the zone enabled to be running

### ISSUE THREAD

**Issue by Kolia56** [rgc99/irrigation_unlimited#88]
## Configuration
controllers:
  name: "Controleur 1"
  all_zones_config:
    show:
      timeline: true
  preamble: "00:01"
  postamble: "00:05"
  entity_id: switch.alimentation_electrovannes
  zones:
    - name: Café François
      entity_id: switch.vanne_atelier_gui
    - name: Maison journalier
      entity_id: switch.vanne_maison_journalier_gui
    - name: Pelouse
      entity_id : switch.vanne_jardin_devant_gui
  sequences:
    - name: nuit
      delay: "00:01"
      schedules:
        - time: "20:30"
      zones:
        - zone_id: 1
          duration: "00:30"
        - zone_id: 2
          duration: "00:20"
    - name: jour
      duration: "00:05"
      delay: "00:55"
      repeat: 7
      schedules: 
        - time: "12:00"
      zones:
        - zone_id: 2
    - name: Pelouse seule
      schedules:
        - time: 02:30
      zones:
        - zone_id: 3
          duration: "00:01"
          delay: "00:01"
        - zone_id: 3
          duration: "00:20"
        
In order to get the manual timer working, the related zone needs to be enabled. By doing so, the sequence will resume automatically at end of the timer, which I do not wan’t precisely because I want to irrigate just for a certain period of time. It seems to me that manual run should independant of the zone status.

**Comment by rgc99** [comment]
Manually starting an individual zone shouldn't be too much of a problem. Same with a disabled sequence. I have some questions however about zones within a sequence that have been disabled. Should these zones be skipped? The zone may have been disabled due to maintenance, a seasonal crop that is resting, a lawn during winter etc.

**Comment by Kolia56** [comment]
I tend to think that if the controller is disabled, manual timing should be indeed forbidden. It acts as a master switch. As for a zone, I do understand the argument regarding zone maintenance, however, I think it should allowed to do manual irrigation even if the zone is disabled. If not, to get manual irrigation working, zone has to be enabled and automatic schedule will resume after the manual irrigation sequence which is not the idea behind « manual ». Same for sequence I guess. 
What is your feeling?

**Comment by rgc99** [comment]
Perhaps zones need to be tri-state rather than binary - enable/disable/manual only. Searching for a suitable terminology here for the third state like sleep, dormant, suspended. Unclear how to implement this but that is the general idea.

**Comment by Kolia56** [comment]
Good idea to have a tri-state logic. I think that manual only is the most understandable since it is directlty related to the manual box where the duration is set. Don't you think?

**Comment by Kolia56** [comment]
Thank you for the nice addition in 2022.11.0
