### ISSUE TITLE
Manual Run time setting is improper

### ISSUE THREAD

**Issue by SuperMaximus1984** [rgc99/irrigation_unlimited#89]
![image](https://user-images.githubusercontent.com/62514634/188960040-c78d65c6-5e6e-41fe-9f06-a34100ac1d4a.png)
Example is above. 
Setting time in Manual Run like 0:10 results in 00:01:00 (1 minute).
What is the proper way to set a manual run for an exact period of time?

**Comment by rgc99** [comment]
Please post your configuration. Ten minutes is the end to end time for a sequence. What happens in the middle will be revealed in the config.

**Comment by rgc99** [comment]
Stale issue.
