### ISSUE TITLE
No module named 'crontab'

### ISSUE THREAD

**Issue by tbaumann** [rgc99/irrigation_unlimited#94]
**Describe the bug**
I just updated the integration with the just released new version and now the component throws an error.
```
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 09:41:18 (1 occurrences)
Last logged: 09:41:18

Setup failed for custom integration irrigation_unlimited: Unable to import component: No module named 'crontab'
```
Looks like maybe there are some missing crontab dependencies. Not sure where that module would come from.

**To Reproduce**

Upgrade irrigation_unlimited and restart HA

**Irrigation Unlimited**
2022.12.0

**HA version**

Home Assistant 2022.12.6 
Supervisor 2022.11.2 
Operating System 9.4 
Frontend 20221213.0 - latest

**Comment by bassguitarist** [comment]
Today I just downloaded again the integration through HACS and this problem disappeared.
Hope this helps someone else.

**Comment by tbaumann** [comment]
Thanks for the hint. It looks like the version `2022.12.0` got pulled. Downloading will pull the older version

**Comment by rgc99** [comment]
Version 2022.12.0 was missing a requirements in the manifest.json file. This release was deleted and new version 2022.12.1 is now available as a pre-release. This will be updated soon to a general release.
