### ISSUE TITLE
Service "irrigation_unlimited.adjust_time" missing

### ISSUE THREAD

**Issue by hvorragend** [rgc99/irrigation_unlimited#95]
**Describe the bug**
I've done several updates at the same time.

- Update core to v2022.12.6.
- And an update of your component to: v2022.12.0

After that, the following error appears in HA repairs:

> Irrigation Unlimited Adjustment uses an unknown service
The automation "Irrigation Unlimited Adjustment" (automation.irrigation_unlimited_adjustment) has an action that calls an unknown service: irrigation_unlimited.adjust_time.
>
> This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.
>
> To fix this error, [edit the automation](https://xxxx/config/automation/edit/IU1653340123453) and remove the action that calls this service.
>
> Click on SUBMIT below to confirm you have fixed this automation.

And it is true. There is the adjust_time-service missing in developer tools, too.

**To Reproduce**
Please see above.

**Expected behavior**
No error. :-)

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 107.x

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 16.2
 - Browser: Safari
 - Version: -

**Additional context**
None

**Comment by rgc99** [comment]
This is a direct result of the component not loading due to a missing requirement. Now fixed and re-released soon.

**Comment by hvorragend** [comment]
Thank you.
